spring.application.name=spring-yt-backendspring-yt-backend

# spring.mvc.static-path-pattern=/static/**
# spring.resources.static-locations=classpath:/static/

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.username=root
spring.datasource.password=Meta@jatan1

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Properties
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# Video Storage Location
files.video=videos/
